[package]
name = "brain"
version = "0.1.0"
authors = ["John Simon <john@whatisaph.one>"]

[dependencies]
arrayvec = "0.4.7"
crossbeam-channel = "0.2.6"
csv = "1.0.2"
itertools = "0.7.8"
lazy_static = "1.1.0"

nalgebra = "0.16.0"
ncollide3d = "0.17.1"

log = "0.4.5"

piston_window = "0.80.0"
piston2d-graphics = "0.26.0"

rlbot = "0.0.6"
chip = { path = "../../chip" }

bakkesmod = { path = "../bakkesmod" }
collect = { path = "../collect" }
simulate = { path = "../simulate" }

[features]
strict = []
