fail_fast: true

repos:
- repo: local
  hooks:
    - id: fmt
      name: fmt
      language: system
      files: '[.]rs$'
      entry: rustup run nightly rustfmt

    # Each package is checked separately because of
    # https://github.com/rust-lang/cargo/issues/5364

    - id: check-brain
      name: check-brain
      language: system
      files: '[.]rs$'
      entry: sh -c '( cd brain && cargo check --all-targets --features strict )'
      pass_filenames: false

    - id: check-brain-test-data
      name: check-brain-test-data
      language: system
      files: '[.]rs$'
      entry: sh -c '( cd brain-test-data && cargo check --all-targets --features strict )'
      pass_filenames: false

    - id: check-collect
      name: check-collect
      language: system
      files: '[.]rs$'
      entry: sh -c '( cd collect && cargo check --all-targets --features strict )'
      pass_filenames: false

    - id: check-common
      name: check-common
      language: system
      files: '[.]rs$'
      entry: sh -c '( cd common && cargo check --all-targets --features strict )'
      pass_filenames: false

    - id: check-dom
      name: check-dom
      language: system
      files: '[.]rs$'
      entry: sh -c '( cd dom && cargo check --all-targets --features strict )'
      pass_filenames: false

    - id: check-oven
      name: check-oven
      language: system
      files: '[.]rs$'
      entry: sh -c '( cd oven && cargo check --all-targets --features strict )'
      pass_filenames: false

    - id: check-play
      name: check-play
      language: system
      files: '[.]rs$'
      entry: sh -c '( cd play && cargo check --all-targets --features strict )'
      pass_filenames: false

    - id: check-simulate
      name: check-simulate
      language: system
      files: '[.]rs$'
      entry: sh -c '( cd simulate && cargo check --all-targets --features strict )'
      pass_filenames: false

    - id: test
      name: test
      language: system
      files: '[.]rs$'
      # Skip the tests which require Rocket League to be running.
      entry: cargo test -- --skip integration_tests
      pass_filenames: false
