[workspace]
members = [
    "brain",
    "brain-test-data",
    "collect",
    "common",
    "oven",
    "play",
    "simulate",
]

[patch.crates-io]
#rlbot = { path = "../rlbot-rust" }
chip = { path = "../chip" }
