[package]
name = "brain-test-data"
version = "0.1.0"
authors = ["John Simon <john@whatisaph.one>"]

[dependencies]
lazy_static = "1.1.0"

nalgebra = "0.16.0"

rlbot = "0.2.0"

collect = { path = "../collect" }

[build-dependencies]
csv = "1.0.2"

[features]
strict = []
