[package]
name = "play"
version = "0.1.0"
authors = ["John Simon <john@whatisaph.one>"]

[dependencies]
chrono = "0.4.6"
lazy_static = "1.1.0"

log = "0.4.4"
env_logger = "0.5.12"

rlbot = "0.0.3"

brain = { path = "../brain" }
collect = { path = "../collect" }
