[package]
name = "collect"
version = "0.1.0"
authors = ["John Simon <john@whatisaph.one>"]

[dependencies]
csv = "1.0.2"
flatbuffers = "0.4.0"
nalgebra = "0.16.0"

rlbot = "0.0.7"

[features]
strict = []
