[package]
name = "common"
version = "0.1.0"
authors = ["John Simon <john@whatisaph.one>"]
edition = "2018"

[dependencies]
lazy_static = "1.1.0"

nalgebra = "0.16.0"

rlbot = "0.2.0"

[dev-dependencies]
chip = "0.0.5"

[features]
strict = []
